authors:
  team:
    name: Team
    description: Creator
    avatar: https://simpleicons.org/icons/materialformkdocs.svg
  andrew:
    name: Andrew Steinmetz
    description: Creator
    avatar: https://github.com/plusmobileapps.png